version: 2.1
jobs:
  # running commands on a basic image
  Hello-World:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  # fetching code from the repo
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Getting the Code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  # running a node container
  Using-Node:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
  Running-Linters:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name: Running the Linter
          command: |
            npm run lint
  Running-Tests:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name: Running the Tests
          command: |
            npm run test
  Now-Complete:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Delivery Complete
          command: |
            echo 'The work is now complete.'

workflows:
  Example-Workflow:
    jobs:
      - Hello-World
      - Fetch-Code:
          requires:
            - Hello-World
      - Using-Node:
          requires:
            - Fetch-Code
      - Running-Linters:
          requires:
            - Using-Node
      - Running-Tests:
          requires:
            - Running-Linters
      - Now-Complete:
          requires:
            - Using-Node
            - Fetch-Code
            - Running-Linters
            - Running-Tests